# Training settings
n_epochs: 2000  # 500 for atm 2000 for cow
batch_size: 8  # 4 for atm 64 for cow training 8 while sampling from atm and 128 for cow sampling
lr: 0.0002
clip_grad: null          # float, null to disable
save_model: True
num_workers: 8 #0
progress_bar: false
weight_decay: 1e-12
optimizer: adamw # adamw,nadamw,nadam => nadamw for large batches, see http://arxiv.org/abs/2102.06356 for the use of nesterov momentum with large batches
seed: 0
